-- Nuevos clientes reales (fuente: Desktop/DOCS MBG/Pipeline Super X .xlsx, hoja Clients)
-- Excluye: filas de prueba del CRM, MBG Trading International (empresa propia),
-- Pradera del Grijalva, Alimentos Masivos y Productos Chata (ya excluidos antes),
-- y los 10 clientes ya cargados previamente.

insert into customers (trade_name, contact_name, email, phone, country) values ('Super Macro Del Poniente', 'Juan Garza', 'jgarza@ecpmx.com', '+52 8112123046', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Cervantes', 'Martha Rodriguez', 'martha.rodriguez@cervantesinc.com', '+1 7603571614', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Comercializadora de Carnes El Ranchito 7', 'Karina Cardenas', 'saulcruzc@gmail.com', '+52 15510428907', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Xalostoc SA de CV', 'Jaqueline calvillo', 'jaqueline@pending.calvillo.com', '+52 15518804071', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Protemeat Internacional', 'Christopher Navarro', 'christopher@pending.com', '+52 12221141851', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Comercializadora Yesaki SA', 'Emilio Morales', 'yesaki@pending.com', '+52 18119997838', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Valvil', 'Javier Valencia', 'javier@pending.com', '+52 13313140761', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Carnes Ramos', 'Patricio Ramos', 'patricio@pending.com', '+52 18116605677', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Silver River Foods Inc', 'Rodrigo Cuenca', 'rodrigo@pending.com', '+52 14491557782', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('PRODUCTOS ALIMENTICIOS NASA', 'Fernando', 'fernando@pending.com', '+52 13314086029', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Jose Manuel Grey Parra', 'Jose Manuel Grey', 'carnesdelasierra@hotmail.com', '+52 13333370690', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Cardenas Alimentos', 'David Rodriguez', 'davi@pending.com', '+52 18110447837', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Rangel Garduño', 'Chris', 'chris@pending.com', '+52 15587911728', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Súper San Francisco de Asis', 'Maria Alpuche', 'maria.alpuche@superaki.mx', '+52 9992977804', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('PPP Foods Comercial', 'Sharon Neris', 'sharon@nortmeat.com', '+52 6671269974', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Super Carnicerias Hernandez', 'Juan Hernandez', 'cotizaciones@sucahersa.com', '+52 4773564768', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Alimentos Orion SA de CV', 'Juan Lopez', 'lopezsa25@hotmail.com', '+52 8180648544', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('RM Carnicos y Alimentos', 'Rocio Marquez Espinosa', 'rociomarquez@rociomarquez.com.mx', '+52 5545356955', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Corporativo Las Dos Marias Sa de CV', 'Marisol Pina', 'corporativodosmarias@prodigy.net.mx', '+52 4444434365', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Gruma De Carnes', 'Lalo', 'comercializacion@grumadecarnes.com.mx', '+52 2297809150', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Grupo Comercial Ofelia', 'Fabiola Diaz', 'rubydiaz@gcofelia.com', '+52 3521327519', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Productos de Bocados Carnicos SA de CV', 'Andrian Gonzalez Rodriguez', 'adrian.gonzalez@proboca.net', '+52 8123706636', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('MR Importadora y Exportadora SA de CV', 'Miguel Angel Cardenas', 'miguelcar9902@gmail.com', '52 5519416884', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('San Francisco del Sabor', 'Juan Jose Romo', 'jromo@sanfranciscods.com', '52 4494415217', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('AB Pollo SA de CV', 'Mariel Arrieta', 'mariel.arrieta@abpollo.com', '52 6142889043', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Comercializadora Nareci SA de CV', 'German Molina', 'german870@hotmail.com', '+52 5529556489', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Maxifrio Congelados', 'Alejandra Gaynord', 'agaynor@maxifrio.com.mx', '+52 6862166092', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Pork Rind SA de CV', 'Miguel Cardin', 'gerencia@porkrind.com.mx', '52 8182360680', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Empacadora Los Molinos SA de CV', 'Allan Longe', 'elm@elp.rr.com', '+1 9157273856', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Alimentos Importados Refrigerados y Congelado', 'Jose Humberto Rodriguez', 'jose_hsv@yahoo.com.mx', '+503 78501243', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Grupo Carnico el Jarocho SA de CV', 'Jose Luis Dorantes', 'luisdm100@hotmail.com', '+52 4494631157', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Carnicerias el Jarocho SA de CV', 'Rogelio Dorantes', 'rogeliodm@msn.com', '+52 9616540658', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Grupo Vermar Pork Meat SA de CV', 'Luis Vera', 'pending@hotmail.com', '+52 6142479239', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Comercializadora de Alimentos Ochoa', 'Alvaro Ochoa', 'mhurtado@ochoadairy.com', '+52 66421819880', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Empacadora Cianca SA de CV', 'Rafael Garcia', 'pending@hotmail.com', '+52 2721030472', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Comercializadora de Carnes Mololo', 'Luis Pochoi', 'pending@hotmail.com', '+52 8343741617', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('El Norteño Especialidad en Carnes', 'Edelimro', 'pending@hotmail.com', '+52 18110161038', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('AYVI SA de CV', 'Miguel Garza', 'mgarza@ayvi.com.mx', '+52 8119904402', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Productos Alimenticios La Unica SA de CV', 'Carlos Garcia', 'cgarcia@la-unica.com', '503 22468700', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Distribuidora Don Omar SA de CV', 'Omar Platero', 'omarplatero@yahoo.com', '503 22660940', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Distribuidora de Santis SA de CV', 'Maria Carmen Bolagnos', 'distribuidoradesantis@gmail.com', '503 22639892', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Diaco SA de CV', 'Karla Mendoza', 'karla.mendoza@diacofoods.sv', '503 78604438', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Qualimentos SA de CV', 'Cecilia Cadena', 'compras@grupoquadrum.com.mx', '+52 6646866602', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Qualtia Alimentos SA de CV', 'Nayeli Elizabeth Alvarado Alejo', 'nayalvar@qualtia.com', '52 5555585077', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Sigma Alimentos SA de CV', 'Isabel Cardenas', 'icardena@sigma-alimentos.com', '52 555555555', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Grupo Marr Distribuidores SA de CV', 'Sarai Bobadilla', 'ypuente@alimentosmam.com', '52 6646881054', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Grupo Yoreme SA de CV', 'Raymundo Osornio', 'rosornio@yoreme.com', '52 6444110212', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Hermanos Jacquez Ochoa', 'Alejandra Jacquez', 'productoshjo@hotmail.com', '+52 16141960315', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Industrializadora de Carnes Strattega SA de C', 'Maria Isabel Treviso', 'mitreviso@bafar.com.mx', '52 6141385034', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Carnes Selectas La Madrilena SA de CV', 'Comprador', 'facturacaslamadrilena@hotmail.com', '52 5555231494', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Obrador San Pancho Sa de CV', 'Christopher Ramirez', 'compras@obradorsanpancho.com', '+52 4494411054', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Omex Alimentos SA de CV', 'Manuel Lozano', 'mlozano@orgumex.com', '+52 3459124000', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Operadora Futurama SA de CV', 'Yenith Perez', 'yenith.perez@alsuper.com', '52 6143429757', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Consorcio Dipcen SA de CV', 'Fernando Cuevas', 'jefeplaneacion@dipcen.com.mx', '+52 5591718350', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('El Charal SA de CV', 'Carlos Zamarripa', 'carlos@charal.com.mx', '52 8181305250', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('El Malecon', 'Jesus Guajardo', 'cpelmalecon@prodigy.net.mx', '52 8787822880', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Embutidos Corona SA de CV', 'Alvaro Aguilar', 'compras@embutidoscorona.com.mx', '+52 3336367015', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Embutidos Servi Carnes SA de CV', 'Eduardo Chavez', 'cpechr@hotmail.com', '+52 13312844600', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Empacadora Rosarito, SA de CV', 'Ivan Salcedo', 'i.salcedo@empacadorarosarito.com.mx', '+52 6646824155', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Kar Fri Alimentos SA de CV', 'Gabriel Elizondo', 'hgabriel@karfri.com', '+52 8183667975', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Atelier Post Co SA de CV', 'luis Ignacio Jimenez', 'luisjimenez.ro@hotmail.com', '+52 5526533570', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Pantages and Associates Inc', 'Jason Pantages', 'jason@pantagesusa.com', '1 6262445501', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Carnes Victoria SA de CV', 'Jesus Flores', 'jflores@carnesvictoria.com', '52 8332261410', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('CY Alimentos SA de CV', 'Carlos Mejia', 'gerenciacompras@cyalimentos.com', '+52 6623869871', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Tiendas Chedraui SA de CV', 'Juan Pablo del Angel', 'jangel@chedraui.com.mx', '52 5511039000', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Chic & Chicken SA de CV', 'Oscar Diaz', 'ods5908@gmail.com', '+52 13336678056', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Abastecedora de Carnes Frescas Roel, SA de CV', 'Jose Fernando Notario Lopez', 'compras@carnesroel.com', '+52 12221688324', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Abastecedora de Materias Primas Agroindustria', 'Ruben Moreno', 'rmampasa@yahoo.com.mx', '52 8677181949', null);
insert into customers (trade_name, contact_name, email, phone, country) values ('Alanis Alimentos SA de CV', 'Sandra Reyes', 'compras@alanisalimentos.mx', '+52 18444149151', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Alimentos Mixoco SA de CV', 'Daniel Xoxocotla', 'daniel@alimentosmixoco.com', '+52 5557483297', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Pollos Vidaurri SA de CV', 'Santos Valdez', 'santos.valdez@vidaurri.mx', '+52 18115993903', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Arlanda SA de CV', 'Berenice Toledo', 'berenice@arlandamx.com', '+52 5548940355', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Intercarnes Distri de Carnes internacionales', 'Paulo Garcia', 'administracion@intercarnes.com.mx', '+52 7225557626', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Manuel Olivos', 'Felipe Olivos', 'nousaemail@hotmail.com', '+52 5543804729', 'México');
insert into customers (trade_name, contact_name, email, phone, country) values ('Impulsora de Bienes Alameda', 'Ceclia Amador', 'cecilia.amador@carnesmuma.com.mx', '52 8717591059', null);
