insert into trucking (name, contact_name, email, country, city, phone) values
('Armstrong Transport Group', 'Andy Clark', 'a.clark@armstrongtransport.com', 'United States', 'Charlotte NC', '+1 8772401181'),
('Best Bay Logistics', 'Alberto Smith', 'alberto@bestbaylogistics.com', 'United States', 'Fontana CA', '+1 8557792378'),
('Cardinal Logistics Managment', 'Jack Solen', 'jack_solen@ryder.com', 'United States', 'San Diego CA', null),
('Carlos Cardenas Freight Broker', 'Carlos Cardenas', 'felreynosa@yahoo.com.mx', 'Mexico', 'Reynosa', '+52 8991175827'),
('Double A Logistics LLC', 'Max Tylor', 'max@doublealogistics.com', 'United States', 'Calexico CA', null),
('Freedom Trans USA', 'Perry Gaffney', 'perry@freedomtransusa.com', 'United States', 'Gainesville GA', '+1 6782070710'),
('Grupo Amigo', 'Alejandro Hernandez', 'alejandro@ibielp.com', 'United States', 'El Paso TX', '+52 6562514259'),
('Key Global Logistics', 'Alex Reed', 'alex@keygloballogistics.com', 'United States', 'Laredo TX', '+1 9563076852'),
('MandG Trucking', 'Rey Ayala', 'reayalajr@hotmail.com', 'United States', 'Laredo TX', '+1 9565327085'),
('Norfleet Transportation And Logistics', 'Claudia Lopez', 'claudia.l@norfleettransportation.com', 'United States', 'AnyCity IA', '+1 2523810420'),
('RIMAC Freight LLC', 'Ricardo M', 'logistics@rimacfreight.com', 'United States', 'Mission TX', null),
('Three Points Logistics LLC', 'Alondra Martinez', 'logistic@3pointsllc.com', 'United States', 'Mission TX', '+1 9564388570'),
('Total Quality Logistics', 'Tommy Phipps', 'tphipps@tql.com', 'United States', 'Altoona IA', '312 834-2979'),
('Transportes Cardenas', 'David Silva', 'transportescardenas15@gmail.com', 'Mexico', 'Reynosa', '+52 8994695862'),
('Transportes Refrigerados Espinoza', 'Juan Carlos Ortiz', 'refrigeradosfi_19@outlook.com', 'Mexico', 'Monterrey', '+52 55555555554'),
('Transportes Sanchez', 'Cristian Sanchez', 'noemail@hotmail.com', 'Mexico', 'Reynosa', '+52 8999601620'),
('Transportes Villalvazo', 'Victor Hugo Villalvazo Sanchez', 'villalvazotransportes@gmail.com', 'Mexico', 'Guadalajara', '+52 3411077930'),
('Unify Logistic Solutions LLC', 'Ryan Knight', 'ryan.knight@unifylogisticsolutions.com', 'United States', 'Any City GA', '+1 2163046370');
