-- ============================================================================
-- 001_business_ids_staging_only.sql
--
-- STAGING ONLY (project geqhjykbxvxugvnpnygn). Adds human-readable business
-- IDs as an ADDITIVE layer on top of the existing UUID primary keys — the
-- UUIDs stay the real primary/foreign keys everywhere, nothing about the 31
-- existing foreign keys changes. business_id is generated by Postgres itself
-- on insert (sequence-backed column default), never supplied by the frontend
-- or by Claude, so it can never collide or be typed wrong.
--
-- Same format across all 5 master-data tables, so the pattern is trivial to
-- repeat for any future table without re-deciding the design:
--   <PREFIX>-000001, zero-padded to 6 digits, one dedicated sequence per table.
--
-- Orders (purchase_orders/sales_orders/freight_orders) already have their own
-- equivalent (order_number, BT-0001...) from 000 — not touched here.
-- ============================================================================

create sequence suppliers_business_id_seq start 1;
alter table suppliers
  add column business_id text not null unique
  default ('SUP-' || lpad(nextval('suppliers_business_id_seq')::text, 6, '0'));

create sequence plants_business_id_seq start 1;
alter table plants
  add column business_id text not null unique
  default ('PLANT-' || lpad(nextval('plants_business_id_seq')::text, 6, '0'));

create sequence products_business_id_seq start 1;
alter table products
  add column business_id text not null unique
  default ('PROD-' || lpad(nextval('products_business_id_seq')::text, 6, '0'));

create sequence customers_business_id_seq start 1;
alter table customers
  add column business_id text not null unique
  default ('CUST-' || lpad(nextval('customers_business_id_seq')::text, 6, '0'));

create sequence providers_business_id_seq start 1;
alter table providers
  add column business_id text not null unique
  default ('PROV-' || lpad(nextval('providers_business_id_seq')::text, 6, '0'));

-- ============================================================================
-- End of 001.
-- ============================================================================
